language: node_js

install:
  - npm install
  - npm install -E openzeppelin-solidity
before_script:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - npm install -g ganache-cli
  - npm install -g npx
  - npm run start &
script:
  - truffle test
  - npm run coverage
after_script: 
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npx semantic-release
